spring:
  datasource:
    url: jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  jwt:
    secret: bHVpemluLXVzZXItc2VydmljZS1zZWNyZXQta2V5LW11aXRv
    expiration-minutes: 120

logging:
  level:
    org.springframework.security: INFO
